version: '3'
 
services:
    app_img_1:
        container_name: ${COMPOSE_PROJECT_NAME}_APP_con_1
        build: ./app1
        expose:
            - ${APP_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APP_1_IP}
    app_img_2:
        container_name: ${COMPOSE_PROJECT_NAME}_APP_con_2
        build: ./app1
        expose:
            - ${APP_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${APP_2_IP}
    haproxy_img:
        build: ./haproxy
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: ${HA_PROXY_IP}
        environment:
            - APP_1_IP=${APP_1_IP}
            - APP_2_IP=${APP_2_IP}
            - APP_EXPOSED_PORT=${APP_EXPOSED_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
